// <auto-generated />
namespace Corlib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _140To1000ForAdText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_140To1000ForAdText));
        
        string IMigrationMetadata.Id
        {
            get { return "201805060458281_140To1000ForAdText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
